# Praktikum 1
Backpropagation adalah sebuah algoritma untuk melatih jaringan saraf tiruan dengan cara mengoreksi kesalahan. Algoritma ini bekerja dengan cara menghitung selisih antara keluaran yang dihasilkan jaringan dan keluaran yang seharusnya (kesalahan), lalu memperbarui bobot dan bias jaringan secara berulang dari keluaran ke masukan untuk meminimalkan kesalahan tersebut. Cara kerja backpropagation

## **Langkah:**
1. Buat dataset sederhana (XOR).
2. Inisialisasi bobot dan bias.
3. Implementasikan forward pass.
4. Hitung error dan lakukan backpropagation.
5. Update bobot menggunakan gradient descent.

In [ ]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 2
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

# Output akhir
print("Prediksi:")
print(a2)

Epoch 0, Loss: 0.2619332267782331
Epoch 1000, Loss: 0.2501244406618378
Epoch 2000, Loss: 0.24906861385493773
Epoch 3000, Loss: 0.2365657738759503
Epoch 4000, Loss: 0.18907027183797684
Epoch 5000, Loss: 0.1391599756557707
Epoch 6000, Loss: 0.042915651887457926
Epoch 7000, Loss: 0.015589450871598111
Epoch 8000, Loss: 0.008556741298306412
Epoch 9000, Loss: 0.005702193777942909
Prediksi:
[[0.05409118]
 [0.93820342]
 [0.93850879]
 [0.0795674 ]]


## Tugas 1
- Ubah jumlah neuron hidden layer menjadi 3.
- Bandingkan hasil loss dengan konfigurasi awal.
- Tambahkan fungsi aktivasi ReLU dan bandingkan hasil.

In [ ]:
# UBAH JUMLAH NEURON HIDDEN MENJADI TIGA
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size_THREE = 3
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size_THREE)
b1 = np.zeros((1, hidden_size_THREE))
W2 = np.random.randn(hidden_size_THREE, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Hitung error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

# Output akhir
print("Prediksi:")
print(a2)

Epoch 0, Loss: 0.25647652368292245
Epoch 1000, Loss: 0.2262062389803688
Epoch 2000, Loss: 0.1663899477210308
Epoch 3000, Loss: 0.144680996453321
Epoch 4000, Loss: 0.13712708440096893
Epoch 5000, Loss: 0.13358385583612614
Epoch 6000, Loss: 0.13158054781656542
Epoch 7000, Loss: 0.1303077695314678
Epoch 8000, Loss: 0.12943330307970377
Epoch 9000, Loss: 0.1287980484692272
Prediksi:
[[0.04680981]
 [0.49570315]
 [0.94936619]
 [0.50418181]]


In [ ]:
# AKTIFASI RELU DAN BANDINGKAN HASIL
import numpy as np
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size_relu = 3
output_size = 1
lr = 0.1
epochs = 10000

# Fungsi Aktivasi ReLU dan Sigmoid
def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return (x > 0).astype(int)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

np.random.seed(42)
W1 = np.random.randn(input_size, hidden_size_relu) * 0.01
b1 = np.zeros((1, hidden_size_relu))
W2 = np.random.randn(hidden_size_relu, output_size) * 0.01
b2 = np.zeros((1, output_size))

# Training
for epoch in range(epochs):

    z1 = np.dot(X, W1) + b1
    a1 = relu(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    error = y - a2
    loss = np.mean(np.square(error))

    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)
    d_a1 = np.dot(d_a2, W2.T) * relu_derivative(z1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        print(f"Epoch {epoch}, Loss: {loss:.6f}")

print("\nOutput Akhir (Prediksi):")
print(a2)
print(f"\nLoss Akhir: {loss:.6f}")

Epoch 0, Loss: 0.250001
Epoch 1000, Loss: 0.250000
Epoch 2000, Loss: 0.250000
Epoch 3000, Loss: 0.250000
Epoch 4000, Loss: 0.250000
Epoch 5000, Loss: 0.250000
Epoch 6000, Loss: 0.250000
Epoch 7000, Loss: 0.250000
Epoch 8000, Loss: 0.250000
Epoch 9000, Loss: 0.250000

Output Akhir (Prediksi):
[[0.49996427]
 [0.50002369]
 [0.4999763 ]
 [0.50003572]]

Loss Akhir: 0.250000


Pada perbandingan dari percobaan awal, ada perubahan nilai pada output prediksi ke-2 dan ketiga, sedangkan pada hidden_input=3, terlihat bahwa prediksi tertinggi berada pada prediksi ke 3. Sedangkan pada Epoch, hasil array prediksi menunjukkan semua hasil hampir sama pada 0.49 atau 0.5.